name: Labels

on:
  push:
    branches: [main, dev]
    paths: [.github/labels.yml]
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
